//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesWebNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageProduct
    {
        public string idImage { get; set; }
        public string idProduct { get; set; }
        public string URLImage { get; set; }
    
        public virtual Product Product { get; set;  }
    }
}
