//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesWebNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type()
        {
<<<<<<< HEAD:ClothesWebNET/Models/Customer.cs
            this.Bill = new HashSet<Bill>();
=======
            this.Products = new HashSet<Product>();
>>>>>>> phudev:ClothesWebNET/Models/Type.cs
        }
    
        public string idType { get; set; }
        public string nameType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
<<<<<<< HEAD:ClothesWebNET/Models/Customer.cs
        public virtual ICollection<Bill> Bill { get; set; }
=======
        public virtual ICollection<Product> Products { get; set; }
>>>>>>> phudev:ClothesWebNET/Models/Type.cs
    }
}
